[package]
name = "harbor"
version = "0.1.0"
edition = "2021"

[dependencies]
httparse = "1.8.0"
json5 = "0.4.1"
once_cell = "1.19.0"
rand = "0.8.5"
serde = { version = "1.0.197", features = ["derive"] }
